---
# tasks file for Redhat
#- name: "Install RedHat packages"
#  package: 
#    pkg: httpd
#    state: present
 
  
- name: "Create document root"
  file:
    path: "/var/www/{{ ap_http_host_dir }}"
    state: directory

- name: "Copy source code/artifacts "          
  copy:
    src: "{{ap_source_code_location}}"
    dest: "/var/www/{{ ap_http_host_dir }}"

- name: "Copy conf file"          
  template:
    src: "web_httpd.conf.j2"
    dest: "/etc/httpd/conf/httpd.conf"
  notify: "Restart Httpd"
  
- name: Enable Httpd
  service:
    name: "httpd"
    enabled: yes

- name: start Httpd
  service:
    name: "httpd"
    state: started
